insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (1, 4, 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh', 1, 16);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (2, 3, 'rutrum nulla nunc purus phasellus in felis', 2, 17);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (3, 1, 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed', 3, 18);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (4, 4, 'posuere felis sed', 4, 19);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (5, 2, 'quis odio consequat varius integer ac', 5, 20);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (6, 2, 'suspendisse potenti cras in purus', 6, 21);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (7, 1, 'lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum', 7, 22);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (8, 1, 'quis lectus suspendisse potenti in', 8, 23);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (9, 5, 'sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices', 9, 24);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (10, 2, 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in', 10, 25);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (11, 1, 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id', 11, 26);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (12, 3, 'in felis eu sapien cursus', 12, 27);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (13, 2, 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 13, 28);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (14, 2, 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce', 14, 29);
insert into RESENAENTITY (id, CALIFICACION, COMENTARIO, HABITACION_ID, VIAJERO_IDUSUARIO) values (15, 4, 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor', 15, 30);
