insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (1, 'Wangcun', '65927 Michigan Alley', 'http://dummyimage.com/101x150.bmp/dddddd/000000',1);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (2, 'Rizokárpaso', '82 Shoshone Alley', 'http://dummyimage.com/242x139.jpg/dddddd/000000',2);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (3, 'Vingåker', '069 Green Ridge Parkway', 'http://dummyimage.com/221x146.bmp/ff4444/ffffff',3);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (4, 'Karobokan', '40 4th Hill', 'http://dummyimage.com/160x234.png/ff4444/ffffff',4);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (5, 'Khorostkiv', '4351 Hovde Lane', 'http://dummyimage.com/176x223.jpg/cc0000/ffffff',5);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (6, 'União', '774 Coleman Hill', 'http://dummyimage.com/143x225.jpg/5fa2dd/ffffff',6);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (7, 'Cilolongokan', '88904 Thierer Circle', 'http://dummyimage.com/140x169.png/ff4444/ffffff',7);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (8, 'Mabini', '79 Towne Center', 'http://dummyimage.com/154x221.bmp/dddddd/000000',8);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (9, 'Turirejo', '34126 8th Hill', 'http://dummyimage.com/241x124.jpg/cc0000/ffffff',9);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (10, 'Palmar de Varela', '4482 Drewry Trail', 'http://dummyimage.com/136x238.bmp/5fa2dd/ffffff',10);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (11, 'Yuanjue', '00732 Armistice Hill', 'http://dummyimage.com/186x230.png/cc0000/ffffff',11);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (12, 'Sukhinichi', '20 Rigney Road', 'http://dummyimage.com/146x147.jpg/cc0000/ffffff',12);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (13, 'Alqueva', '37 Maryland Plaza', 'http://dummyimage.com/112x174.jpg/cc0000/ffffff',13);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (14, 'Takikawa', '7 Carey Parkway', 'http://dummyimage.com/142x172.png/5fa2dd/ffffff',14);
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen,ANFITRION_IDUSUARIO) values (15, 'Talitsy', '8 Schurz Park', 'http://dummyimage.com/216x192.bmp/5fa2dd/ffffff',15);