insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (1, 'Wangcun', '65927 Michigan Alley', 'http://dummyimage.com/101x150.bmp/dddddd/000000');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (2, 'Rizokárpaso', '82 Shoshone Alley', 'http://dummyimage.com/242x139.jpg/dddddd/000000');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (3, 'Vingåker', '069 Green Ridge Parkway', 'http://dummyimage.com/221x146.bmp/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (4, 'Karobokan', '40 4th Hill', 'http://dummyimage.com/160x234.png/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (5, 'Khorostkiv', '4351 Hovde Lane', 'http://dummyimage.com/176x223.jpg/cc0000/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (6, 'União', '774 Coleman Hill', 'http://dummyimage.com/143x225.jpg/5fa2dd/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (7, 'Cilolongokan', '88904 Thierer Circle', 'http://dummyimage.com/140x169.png/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (8, 'Mabini', '79 Towne Center', 'http://dummyimage.com/154x221.bmp/dddddd/000000');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (9, 'Turirejo', '34126 8th Hill', 'http://dummyimage.com/241x124.jpg/cc0000/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (10, 'Palmar de Varela', '4482 Drewry Trail', 'http://dummyimage.com/136x238.bmp/5fa2dd/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (11, 'Yuanjue', '00732 Armistice Hill', 'http://dummyimage.com/186x230.png/cc0000/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (12, 'Sukhinichi', '20 Rigney Road', 'http://dummyimage.com/146x147.jpg/cc0000/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (13, 'Alqueva', '37 Maryland Plaza', 'http://dummyimage.com/112x174.jpg/cc0000/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (14, 'Takikawa', '7 Carey Parkway', 'http://dummyimage.com/142x172.png/5fa2dd/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (15, 'Talitsy', '8 Schurz Park', 'http://dummyimage.com/216x192.bmp/5fa2dd/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (16, 'Oslo', '3 Commercial Way', 'http://dummyimage.com/135x213.jpg/5fa2dd/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (17, 'Tarogong', '649 Thompson Alley', 'http://dummyimage.com/201x199.bmp/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (18, 'Carlsbad', '273 Corscot Street', 'http://dummyimage.com/244x110.png/dddddd/000000');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (19, 'Petaling Jaya', '4 Hoard Road', 'http://dummyimage.com/233x189.jpg/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (20, 'Solosolo', '4062 Vahlen Lane', 'http://dummyimage.com/140x129.png/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (21, 'Lavras da Mangabeira', '27 Hauk Place', 'http://dummyimage.com/115x138.png/dddddd/000000');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (22, 'Donghu', '421 8th Center', 'http://dummyimage.com/235x157.bmp/cc0000/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (23, 'Congas', '60094 Forest Dale Drive', 'http://dummyimage.com/202x198.bmp/cc0000/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (24, 'São Sebastião do Caí', '4 Bonner Hill', 'http://dummyimage.com/216x249.png/dddddd/000000');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (25, 'Wangshi', '5 Hazelcrest Crossing', 'http://dummyimage.com/103x224.jpg/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (26, 'Wuhu', '693 Daystar Park', 'http://dummyimage.com/107x226.jpg/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (27, 'Jinyuan', '7 Pankratz Trail', 'http://dummyimage.com/250x202.bmp/ff4444/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (28, 'Ketapang', '9742 Summit Street', 'http://dummyimage.com/130x227.bmp/5fa2dd/ffffff');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (29, 'Świebodzice', '14517 Walton Park', 'http://dummyimage.com/195x239.bmp/dddddd/000000');
insert into VIVIENDAENTITY (id, ciudad, direccion, rutaImagen) values (30, 'Kresna', '59 Golden Leaf Junction', 'http://dummyimage.com/180x108.bmp/ff4444/ffffff');